# Generated by Django 5.2.4 on 2025-07-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama platform, cth: Instagram', max_length=100, unique=True)),
                ('url', models.URLField(help_text='URL utama platform')),
                ('last_scraped', models.DateTimeField(blank=True, help_text='Kapan terakhir kali platform ini di-scrape', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(help_text='URL unik dari postingan', unique=True)),
                ('caption', models.TextField(blank=True, help_text='Teks atau caption dari postingan', null=True)),
                ('media_url', models.URLField(blank=True, help_text='URL ke gambar atau video utama', null=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Waktu postingan ini diunggah', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.scrapedpost')),
            ],
        ),
        migrations.CreateModel(
            name='TargetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username atau nama unik akun', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Nama tampilan akun', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email yang ditemukan (jika ada)', max_length=254, null=True)),
                ('domisili', models.CharField(blank=True, help_text='Domisili yang ditemukan (jika ada)', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, help_text='Teks bio atau deskripsi profil', null=True)),
                ('website_url', models.URLField(blank=True, help_text='URL website yang ada di bio', null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='Waktu data profil ini disimpan')),
                ('platform', models.ForeignKey(help_text='Platform asal profil ini', on_delete=django.db.models.deletion.CASCADE, to='core.platform')),
            ],
        ),
        migrations.AddField(
            model_name='scrapedpost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.targetprofile'),
        ),
    ]
