# Generated by Django 5.2.4 on 2025-08-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpost',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi lengkap video', null=True),
        ),
    ]
