# Generated by Django 5.2.4 on 2025-08-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scrapedpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcomment',
            name='follow_up',
            field=models.BooleanField(default=False, help_text='Tandai jika komentar ini perlu di-follow up'),
        ),
    ]
